# Generated by Django 4.2 on 2023-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DR_detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datas",
            name="Cpassword",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="datas",
            name="Password",
            field=models.CharField(default="", max_length=20),
        ),
    ]
